In [3]:
def add_numbers(x,y):
    return x+y

add_numbers(1,2)

3

In [7]:
def add_numbers(x,y,z=None):
    if z==None:
        return x+y
    else:
        return x+y+z

add_numbers(1,2,3)

6

In [8]:
def add_numbers(x,y,z=None,flag=False):
    if(flag):
        print ('Flag is true!')
    if z==None:
        return x+y
    else:
        return x+y+z
print (add_numbers(1,2,flag=True))

Flag is true!
3


In [9]:
print (add_numbers(1,2,3,flag=True))

Flag is true!
6


In [10]:
type ('this is a string!')

str

In [11]:
type(None)

NoneType

In [12]:
type(1)

int

In [13]:
type(1.0)

float

In [14]:
type(add_numbers)

function

In [15]:
x=(1,2,'a','b')
type(x)

tuple

In [17]:
x = [1,2,'a','b']
type (x)

list

In [18]:
x.append(3.3)
print(x)

[1, 2, 'a', 'b', 3.3]


In [19]:
for item in x:
    print(item)

1
2
a
b
3.3


In [23]:
x = 'Dr. Christopher Brooks'

print(x[4:-7])

Christopher


In [30]:
firstname='Chris'
lastname='Brooks'

print(firstname + ' ' + lastname)
print (firstname*3)
print('Chris' in firstname)

Chris Brooks
ChrisChrisChris
True


In [33]:
firstname = 'Chris a b Brooks'.split(' ')[0]
lastname = 'Chris a Brooks'.split(' ')[-1]
print(firstname)
print(lastname)

Chris
Brooks


In [36]:
'Chris' + str(2) 

'Chris2'

In [39]:
x = {'chris':'bchris@umich.edu',
    'bill':'bli@umich.edu'}
x['chris']

'bchris@umich.edu'

In [40]:
x['kelvin'] = None
x

{'chris': 'bchris@umich.edu', 'bill': 'bli@umich.edu', 'kelvin': None}

In [41]:
for name in x:
    print(x[name])

bchris@umich.edu
bli@umich.edu
None


In [43]:
for email in x.values():
    print(email)

bchris@umich.edu
bli@umich.edu
None


In [47]:
for a, b in x.items():
    print(a)
    print(b)

chris
bchris@umich.edu
bill
bli@umich.edu
kelvin
None


In [48]:
x  = ('chris','Brooks','cbrooks@umich.edu')
fname,lastname,email = x
fname

'chris'

In [49]:
print('ch'+str(2))

ch2


In [50]:
sales ={'price':3,
       'num_items':4,
       'person':'Chris'}

Sentence = '{} bought {} items at a price of {} each '

print(
    Sentence.format
        (
            sales['person'],
            sales['num_items'],
            sales['price']            
        )
     )

Chris bought 4 items at a price of 3 each 


In [51]:
import datetime as dt
import time as tm

In [52]:
tm.time()

1573939843.6170564

In [53]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2019, 11, 16, 14, 31, 20, 857102)

In [54]:
delta = dt.timedelta(100)
delta

datetime.timedelta(days=100)

In [55]:
today = dt.date.today()
print(today - delta)

2019-08-08


In [56]:
today > today - delta

True

In [57]:
today = dt.date.today


In [58]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min,store1,store2)
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


In [69]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

answer = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]

answer[:50]

['aa00',
 'aa01',
 'aa02',
 'aa03',
 'aa04',
 'aa05',
 'aa06',
 'aa07',
 'aa08',
 'aa09',
 'aa10',
 'aa11',
 'aa12',
 'aa13',
 'aa14',
 'aa15',
 'aa16',
 'aa17',
 'aa18',
 'aa19',
 'aa20',
 'aa21',
 'aa22',
 'aa23',
 'aa24',
 'aa25',
 'aa26',
 'aa27',
 'aa28',
 'aa29',
 'aa30',
 'aa31',
 'aa32',
 'aa33',
 'aa34',
 'aa35',
 'aa36',
 'aa37',
 'aa38',
 'aa39',
 'aa40',
 'aa41',
 'aa42',
 'aa43',
 'aa44',
 'aa45',
 'aa46',
 'aa47',
 'aa48',
 'aa49']

In [70]:
import numpy as np
list = [1,2,3]
x = np.array(list)
x

array([1, 2, 3])

In [73]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
m.shape

(2, 3)

In [76]:
n = np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [78]:
n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [79]:
o = np.linspace(0,4,9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [80]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [81]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [82]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [83]:
np.diag(x)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [84]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [85]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [88]:
p = np.ones([2,3],int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [89]:
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [90]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [91]:
s[-1]

144

In [92]:
s[-5]

64

In [94]:
s[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

In [136]:
r = np.arange(36)
r.resize((6,6))
print(r)
r[::7]
#r[0:6, ::-7]
#r.reshape(36)[::7]
#r[2:4,2:4]
#r[[2,3],[2,3]]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[0, 1, 2, 3, 4, 5]])

In [96]:
r[2,2]

14

In [97]:
r[3,3:6]

array([21, 22, 23])

In [98]:
r[r>30]

array([31, 32, 33, 34, 35])

In [102]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [105]:
r2[:]=0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [106]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [108]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [109]:
r_copy[:]=10
print(r_copy,'\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [111]:
test = np.random.randint(0,10,(4,3))
test

array([[4, 6, 3],
       [0, 8, 6],
       [3, 9, 1],
       [7, 4, 8]])

In [112]:
for row in test:
    print(row)

[4 6 3]
[0 8 6]
[3 9 1]
[7 4 8]


In [115]:
len(test)

4

In [116]:
for i in range(len(test)):
    print(test[i])

[4 6 3]
[0 8 6]
[3 9 1]
[7 4 8]


In [118]:
for i, row in enumerate(test):
    print('row',i,'is',row)

row 0 is [4 6 3]
row 1 is [0 8 6]
row 2 is [3 9 1]
row 3 is [7 4 8]


In [119]:
test2 = test**2
test2

array([[16, 36,  9],
       [ 0, 64, 36],
       [ 9, 81,  1],
       [49, 16, 64]], dtype=int32)

In [120]:
for i,j in zip(test,test2):
    print(i,'+',j,'=',i+j)

[4 6 3] + [16 36  9] = [20 42 12]
[0 8 6] + [ 0 64 36] = [ 0 72 42]
[3 9 1] + [ 9 81  1] = [12 90  2]
[7 4 8] + [49 16 64] = [56 20 72]


In [121]:
['a','b']+[1,2]

['a', 'b', 1, 2]

In [122]:
type(lambda x:x+1)

function

In [138]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [139]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [141]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

In [142]:
s[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

In [143]:
r=np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [154]:
r[::3]

array([[ 0,  1,  2,  3,  4,  5],
       [18, 19, 20, 21, 22, 23]])

In [145]:
r[3,3:6]

array([21, 22, 23])

In [146]:
r[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [147]:
r[-1,::2]

array([30, 32, 34])

In [157]:
import pandas as pd
animals = ['cat','dog',None]
pd.Series(animals)

0     cat
1     dog
2    None
dtype: object

In [158]:
numbers = [1,2,None]
pd.Series(numbers)

0    1.0
1    2.0
2    NaN
dtype: float64

In [159]:
import numpy as np
np.nan==None

False

In [219]:
sports = {
    'a':'america',
    'b':'british',
    'c':'china'
}
s = pd.Series(sports)
s

a    america
b    british
c      china
dtype: object

In [223]:
a = s.index.tolist()
a[0]

'a'

In [162]:
s = pd.Series(['a','b'],index=[0,1])
s

0    a
1    b
dtype: object

In [163]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports, index=['Golf', 'Sumo', 'Hockey'])
s

Golf      Scotland
Sumo         Japan
Hockey         NaN
dtype: object

In [164]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [168]:
s.iloc[3]

'South Korea'

In [169]:
s.loc['Golf']

'Scotland'

In [170]:
s['Golf']

'Scotland'

In [175]:
sports = {99:'Bhutan', 100:'Scotland'}
s = pd.Series(sports)
s

99       Bhutan
100    Scotland
dtype: object

In [179]:
s.iloc[0]

'Bhutan'

In [180]:
s=pd.Series([100,120])
s

0    100
1    120
dtype: int64

In [181]:
import numpy as np
total = np.sum(s)
total

220

In [182]:
s=pd.Series(np.random.randint(0,1000,10000))
s.head()

0    906
1    986
2    359
3    548
4    331
dtype: int32

In [186]:
len(s)

10000

In [188]:
summary = np.sum(s)
summary

4990308

In [189]:
s+=2
s.head()

0    908
1    988
2    361
3    550
4    333
dtype: int32

In [190]:
s = pd.Series([1,2,3])
s.loc['animals']='bears'
s

0              1
1              2
2              3
animals    bears
dtype: object

In [192]:
original_sports = pd.Series({'Archery': 'Bhutan',
                             'Golf': 'Scotland',
                             'Sumo': 'Japan',
                             'Taekwondo': 'South Korea'})
cricket_loving_countries = pd.Series(['Australia',
                                      'Barbados',
                                      'Pakistan',
                                      'England'], 
                                   index=['Cricket',
                                          'Cricket',
                                          'Cricket',
                                          'Cricket'])
all_countries = original_sports.append(cricket_loving_countries)

In [193]:
original_sports

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [194]:
cricket_loving_countries

Cricket    Australia
Cricket     Barbados
Cricket     Pakistan
Cricket      England
dtype: object

In [195]:
all_countries

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
Cricket        Australia
Cricket         Barbados
Cricket         Pakistan
Cricket          England
dtype: object

In [196]:
all_countries.loc['Cricket']

Cricket    Australia
Cricket     Barbados
Cricket     Pakistan
Cricket      England
dtype: object

In [197]:
import pandas as pd
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])
df.head()

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

In [198]:
df.loc['Store 2']

Name                  Vinod
Item Purchased    Bird Seed
Cost                      5
Name: Store 2, dtype: object

In [199]:
type(df.loc['Store 2'])

pandas.core.series.Series

In [200]:
df.loc['Store 1']

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5

In [201]:
df.loc['Store 1','Cost']

Store 1    22.5
Store 1     2.5
Name: Cost, dtype: float64

In [202]:
df.T

Store 1       Store 1    Store 2
Name               Chris         Kevyn      Vinod
Item Purchased  Dog Food  Kitty Litter  Bird Seed
Cost                22.5           2.5          5

In [203]:
df.T.loc['Cost']

Store 1    22.5
Store 1     2.5
Store 2       5
Name: Cost, dtype: object

In [204]:
df['Cost']

Store 1    22.5
Store 1     2.5
Store 2     5.0
Name: Cost, dtype: float64

In [205]:
df.loc['Store 1']['Cost']

Store 1    22.5
Store 1     2.5
Name: Cost, dtype: float64

In [206]:
df.loc[:,['Name','Cost']]

Name  Cost
Store 1  Chris  22.5
Store 1  Kevyn   2.5
Store 2  Vinod   5.0

In [207]:
df.drop('Store 1')

Name Item Purchased  Cost
Store 2  Vinod      Bird Seed   5.0

In [209]:
df

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

In [210]:
copy_df = df.copy()
copy_df = copy_df.drop('Store 1')
copy_df

Name Item Purchased  Cost
Store 2  Vinod      Bird Seed   5.0

In [212]:
copy_df.drop

<bound method DataFrame.drop of           Name Item Purchased  Cost
Store 2  Vinod      Bird Seed   5.0>

In [213]:
del copy_df['Name']
copy_df

Item Purchased  Cost
Store 2      Bird Seed   5.0

In [214]:
df['Location']=None
df

Name Item Purchased  Cost Location
Store 1  Chris       Dog Food  22.5     None
Store 1  Kevyn   Kitty Litter   2.5     None
Store 2  Vinod      Bird Seed   5.0     None